thingsboard:
  host: dev.zhiyesoft.com
  port: 41883
  remoteConfiguration: true
  security:
    accessToken: x4Za3Fby0RAuJVq7Mta1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
#
#  -
#    name: MQTT Broker Connector
#    type: mqtt
#    configuration: mqtt.json
#
  -
    name: TCP Usr Connector
    type: tcp
    configuration: usr.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua
#    configuration: opcua.json
#
#  -
#    name: BLE Connector
#    type: ble
#    configuration: ble.json
#
#  -
#    name: REQUEST
#    type: request
#    configuration: request.json
#
#  -
#    name: Custom Serial Connector
#    type: serial
#    configuration: custom_serial.json
#    class: CustomSerialConnector